ORDER_STATUS_PENDING_VALIDATION = 1
ORDER_STATUS_PENDING_APPROVAL = 2
ORDER_STATUS_PENDING_FULFILLMENT = 3
ORDER_STATUS_FULFILLED = 4
ORDER_STATUS_CANCELED = 5
ORDER_STATUS_ON_HOLD = 6

ORDER_STATUS_NAME_MAPPING = {
    ORDER_STATUS_PENDING_VALIDATION: 'Pending Validation',
    ORDER_STATUS_PENDING_APPROVAL: 'Pending Approval',
    ORDER_STATUS_PENDING_FULFILLMENT: 'Pending Fulfillment',
    ORDER_STATUS_FULFILLED: 'Fulfilled',
    ORDER_STATUS_CANCELED: 'Canceled',
    ORDER_STATUS_ON_HOLD: 'On Hold',
}
