"""empty message

Revision ID: 05850b13b7aa
Revises: 69bd15eb0601
Create Date: 2024-09-09 20:32:41.900949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05850b13b7aa'
down_revision: Union[str, None] = '69bd15eb0601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('status_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_status_fkey', 'user', type_='foreignkey')
    op.create_foreign_key('user_status_id_fkey', 'user', 'user_status', ['status_id'], ['id'])
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('user_status_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key('user_status_fkey', 'user', 'user_status', ['status'], ['id'])
    op.drop_column('user', 'status_id')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
